### ISSUE TITLE
管理者機能を実装

### ISSUE THREAD

**Issue by suppin** [MarchColleagues/FlowerHappy#2]
- [x] Userモデルを作成
- [x] Adminモデルを作成
- [x] Adminはアプリ上から登録できないようにする
- [x] シードデータで管理者を登録できるようにする
- [x] `/admin`のURLで管理画面のトップページを作成する
- [x] 管理者しか管理画面にアクセスできないようにする
- [x] 管理者以外がアクセスした場合はトップページにリダイレクトさせる

**Comment by tsukamotohiroaki** [comment]
管理者login画面変更#10
